import crypto from 'crypto';

const ALGORITHM = 'aes-256-gcm';

// We must ensure ENCRYPTION_KEY is exactly 32 bytes for AES-256
function getEncryptionKey(): Buffer {
  const keyStr = process.env.ENCRYPTION_KEY;
  if (!keyStr) {
    throw new Error('ENCRYPTION_KEY environment variable is missing.');
  }
  // Ensure the key is exactly 32 bytes by hashing it if necessary, or padding/truncating
  // A simple approach is to use a sha256 hash of the provided key string
  return crypto.createHash('sha256').update(String(keyStr)).digest();
}

/**
 * Encrypts a string (e.g., an OAuth access token)
 * @returns A string in the format "iv:authTag:encryptedText"
 */
export function encryptToken(text: string): string {
  if (!text) return text;
  
  const iv = crypto.randomBytes(12);
  const key = getEncryptionKey();
  
  const cipher = crypto.createCipheriv(ALGORITHM, new Uint8Array(key), new Uint8Array(iv));
  
  let encrypted = cipher.update(text, 'utf8', 'hex');
  encrypted += cipher.final('hex');
  
  const authTag = cipher.getAuthTag().toString('hex');
  
  return `${iv.toString('hex')}:${authTag}:${encrypted}`;
}

/**
 * Decrypts a string generated by `encryptToken`
 */
export function decryptToken(encryptedString: string): string {
  if (!encryptedString) return encryptedString;
  if (!encryptedString.includes(':')) {
    // Fallback: if it's not encrypted (e.g. from an old DB entry), just return it
    return encryptedString;
  }

  try {
    const parts = encryptedString.split(':');
    if (parts.length !== 3) {
      throw new Error('Invalid encrypted string format');
    }

    const [ivHex, authTagHex, encryptedTextHex] = parts;
    const iv = Buffer.from(ivHex, 'hex');
    const authTag = Buffer.from(authTagHex, 'hex');
    const key = getEncryptionKey();

    const decipher = crypto.createDecipheriv(ALGORITHM, new Uint8Array(key), new Uint8Array(iv));
    decipher.setAuthTag(new Uint8Array(authTag));

    let decrypted = decipher.update(encryptedTextHex, 'hex', 'utf8');
    decrypted += decipher.final('utf8');

    return decrypted;
  } catch (err) {
    console.error('Failed to decrypt token:', err);
    throw new Error('Failed to decrypt token');
  }
}
